name: Template-OG
author: NotAlexNoyle
description: A blank plugin for TrueOG from which to base other plugins off of.
website: https://github.com/true-og/Template-OG/
version: '${version}'
api-version: '${apiVersion}'
main: plugin.TemplateOG
depend: 
#  - DiamondBank-OG
  - Utilities-OG
